apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: example-allowed
spec:
  minMasterVersion: "1.19"
  location: asia-southeast1
  initialNodeCount: 1
  defaultMaxPodsPerNode: 3
  nodeLocations:
    - asia-southeast1-a
    - asia-southeast1-b
    - asia-southeast1-c
  workloadIdentityConfig:
    identityNamespace: myexampleproject.svc.id.goog
  networkingMode: VPC_NATIVE
  networkRef:
    name: containercluster-dep-vpcnative
  subnetworkRef:
    name: containercluster-dep-vpcnative
  ipAllocationPolicy:
    servicesSecondaryRangeName: servicesrange
    clusterSecondaryRangeName: clusterrange
  clusterAutoscaling:
    enabled: true
    autoscalingProfile: BALANCED
    resourceLimits:
    - resourceType: cpu
      maximum: 100
      minimum: 10
    - resourceType: memory
      maximum: 1000
      minimum: 100
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: 00:00
  releaseChannel:
    channel: STABLE
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: containercluster-dep-vpcnative
  enableBinaryAuthorization: true
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  addonsConfig:
    networkPolicyConfig:
      disabled: false
    dnsCacheConfig:
      enabled: true
    configConnectorConfig:
      enabled: true
  networkPolicy:
    enabled: true
  podSecurityPolicyConfig:
    enabled: true
  verticalPodAutoscaling:
    enabled: true